import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";
import CopyRightFooter from "./components/CopyRightFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-cover bg-no-repeat backdrop-blur-50 w-full h-screen`}
        style={{
          backgroundImage: `url('/images/icons/svg/backgroundimage.svg')`,
        }}
      >
        <div className="w-full h-screen">
          <Navbar />
          <div className="flex">
            <Sidebar />
            <div className="flex-1">
              {children}
              <CopyRightFooter />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
