name: Deploy Nodejs Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub 
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}       
      - name: Build docker image
        run: sudo docker build -t kranthi1207/rp-frontend-artifact .  
      - name: Publish image to docker hub 
        run: sudo docker push kranthi1207/rp-frontend-artifact:latest 
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to docker hub 
        run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} 
      - name: Pull image from docker hub
        run: sudo docker pull kranthi1207/rp-frontend-artifact:latest
      - name: Delete old container
        run: sudo docker rm -f rp-frontend-artifact
      - name: Run docker container
        run: sudo docker run -itd -p 8080:3000 --name rp-frontend-artifact-container kranthi1207/rp-frontend-artifact:latest
