name: Deploy FrontEnd Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install npm 
        run: npm install --production
        
    #  - name: Login to Dockerhub
     #   uses: docker/login-action@v1
      #  with:
       #   username:${{secrets.DOCKERHUB_USERNAME}}
        #  password:${{secrets.DOCKERHUB_TOKEN}}

      #- name: Build Docker Image
       # uses: docker build -t RT-FRONTEND .

      #- name: push docker image
       # uses: docker/build-push-action@v2
        #with:
         # push: true
          #tags: kranthi1207/RP_Frontend:latest
          
#deploy: 
 #       steps:
  #      - name: SSH into server
   #       uses: ssh username@ip -p password
    #    - name: Pull the image
     #     uses: docker pull RT-FRONTEND
      #  - name: Run the container
       #   uses: docker run -itd -name RT-frontend-UI -p 8080:3000 RT-FRONTEND
        #- name: Verify the service
         # uses: docker ps | grep "RT-frontend-UI"
